version: "3.9"

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: platformops_mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

      
#docker compose -f docker-compose.smtp.yml up -d
